entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

providers:
  file:
    directory: /etc/traefik/file-provider
    watch: true
  docker:
    exposedByDefault: false
    watch: true

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: letsencrypt@rejaku.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
