stages:
  - deploy

image: alpine:latest

deploy:prod:
  stage: deploy
  tags:
    - docker
  environment:
    name: Production
    url: "https://watchlist.akiba.games/"
  before_script:
  - 'which ssh-agent || ( apk add openssh-client rsync )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$PROD_KEY")
    - ls -l
    - rsync -avh --delete --exclude-from=rsync-excludes.txt . gitlab@ssh.akiba.games:/opt/itchbot/
    - ssh gitlab@ssh.akiba.games 'cd /opt/itchbot && docker compose pull && docker compose up -d'
