x-app: &app
  image: ghcr.io/akibaat/itchbot-docker/python:0.6
  depends_on:
    - db
x-db: &db
  image: postgres:16.2
x-pgbouncer: &pgbouncer
  image: edoburu/pgbouncer
  depends_on:
    - postgres

services:
  bot:
    <<: *app
    networks:
      - shared
    volumes:
      - ./app:/app
    command: ["python", "main.py"]
    environment:
      - DB=${DB:-itchbot}
      - DB_USER=${DB_USER:-itchbot}
      - DB_PASSWORD=${DB_PASSWORD:-docker}
      - PROXY_LIST
      - PROXY_USER
      - PROXY_PASSWORD
      - DISCORD_API_KEY
      - ITCH_API_KEY
      - ITCH_COLLECTION_ID
      - ITCH_USER
      - ITCH_PASSWORD
      - SDL_VIDEODRIVER=dummy
      - PYTHONUNBUFFERED=1
  php-fpm:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: php.Dockerfile
    networks:
      - shared
      - web
    volumes:
      - ./web:/app
    environment:
      - APP_NAME="FVN.li"
      - APP_URL=https://${DOMAIN}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB:-itchbot}
      - DB_USERNAME=${DB_USER:-itchbot}
      - DB_PASSWORD=${DB_PASSWORD:-docker}
      - REDIS_HOST=redis
  web:
    image: nginx:latest
    depends_on:
      - php-fpm
    networks:
      - shared
      - web
    volumes:
      - ./web:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - DB=${DB:-itchbot}
      - DB_USER=${DB_USER:-itchbot}
      - DB_PASSWORD=${DB_PASSWORD:-docker}
      - CADDY_GLOBAL_OPTIONS=debug
      - SERVER_NAME=${DOMAIN}:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.web.tls=false"
  postgres:
    <<: *db
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "shared_buffers=6GB"
    networks:
      - shared
    environment:
      - POSTGRES_DB=${DB:-itchbot}
      - POSTGRES_USER=${DB_USER:-itchbot}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-docker}
    volumes:
      - db:/var/lib/postgresql/data
      - ./backup:/backup
  db:
    <<: *pgbouncer
    networks:
      - shared
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - AUTH_TYPE=scram-sha-256
      - DB_HOST=postgres
      - DB_NAME=${DB:-itchbot}
      - DB_USER=${DB_USER:-itchbot}
      - DB_PASSWORD=${DB_PASSWORD:-docker}
  redis:
    image: redis:latest
    networks:
      - shared
    volumes:
      - redis:/data


volumes:
  redis:
  db:

networks:
  shared:
    name: shared
  web:
    name: web
    external: true
