services:
  traefik:
    labels:
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
    restart: unless-stopped
  app:
    restart: unless-stopped
  db:
    restart: unless-stopped
