services:
  traefik:
    volumes:
      - /opt/persistent/traefik/acme.json:/acme.json
    labels:
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
    restart: unless-stopped
  app:
    restart: unless-stopped
  db:
    restart: unless-stopped
