x-app: &app
  image: registry.gitlab.com/rejaku/itchbot-docker/app:0.43
  depends_on:
    - db
x-db: &db
  image: mariadb:10.11

services:
  bot:
    <<: *app
    networks:
      - shared
    environment:
      - DB=${DB:-itchbot}
      - DB_USER=${DB_USER:-docker}
      - DB_PASSWORD=${DB_PASSWORD:-docker}
      - DISCORD_API_KEY
      - ITCH_API_KEY
      - ITCH_COLLECTION_ID
  web:
    <<: *app
    networks:
      - shared
      - web
    command: ["python", "web.py"]
    environment:
      - DB=${DB:-itchbot}
      - DB_USER=${DB_USER:-docker}
      - DB_PASSWORD=${DB_PASSWORD:-docker}
      - DISCORD_API_KEY
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - DISCORD_REDIRECT_URI=https://${DOMAIN}/callback
      - FLASK_SECRET
      - ITCH_API_KEY
      - ITCH_COLLECTION_ID
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.web.tls=true"
  db:
    <<: *db
    networks:
      - shared
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-docker}
      - MARIADB_DATABASE=${DB:-itchbot}
      - MARIADB_USER=${DB_USER:-docker}
      - MARIADB_PASSWORD=${DB_PASSWORD:-docker}
    volumes:
      - db:/var/lib/mysql

volumes:
  redis:
  db:

networks:
  shared:
    name: shared
  web:
    name: web
    external: true
