x-traefik: &traefik
  image: traefik:2.10

services:
  traefik:
    <<: *traefik
    networks:
      web:
        aliases:
          - "${DOMAIN}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./docker/run/traefik/conf:/etc/traefik

networks:
  web:
    external: false
