x-traefik: &traefik
  image: traefik:2.9
x-app: &app
  image: registry.gitlab.com/rejaku/itchbot-docker/app:0.18
  # Ignore ARM64 builds for now
  platform: linux/amd64
  depends_on:
    - db
x-db: &db
  image: mariadb:10.10

services:
  traefik:
    <<: *traefik
    networks:
      shared:
        aliases:
          - "${DOMAIN1}"
          - "${DOMAIN2}"
          - "${DOMAIN3}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./docker/run/traefik/conf:/etc/traefik
  bot:
    <<: *app
    networks:
      - shared
    environment:
      - DB=${DB:-itchbot}
      - DB_USER=${DB_USER:-docker}
      - DB_PASSWORD=${DB_PASSWORD:-docker}
      - DISCORD_API_KEY
      - ITCH_API_KEY
      - ITCH_COLLECTION_ID
  web:
    <<: *app
    networks:
      - shared
    command: ["python", "web.py"]
    environment:
      - DB=${DB:-itchbot}
      - DB_USER=${DB_USER:-docker}
      - DB_PASSWORD=${DB_PASSWORD:-docker}
      - DISCORD_API_KEY
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - DISCORD_REDIRECT_URI=https://${DOMAIN2}/callback
      - FLASK_SECRET
      - ITCH_API_KEY
      - ITCH_COLLECTION_ID
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${DOMAIN1}`) || Host(`${DOMAIN2}`) || Host(`${DOMAIN3}`)"
      - "traefik.http.routers.web.tls=true"
  db:
    <<: *db
    networks:
      - shared
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-docker}
      - MARIADB_DATABASE=${DB:-itchbot}
      - MARIADB_USER=${DB_USER:-docker}
      - MARIADB_PASSWORD=${DB_PASSWORD:-docker}
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

networks:
  shared:
    name: shared
